### ISSUE TITLE
Issue uploading polygon shapefiles

### ISSUE THREAD

**Issue by hannahcunning** [StraboSpot/strabo-desktop#17]
I have been having a problem uploading shapefiles into Strabospot to be used for Field Camp. The polygons are separated, and should look like this:
![image001](https://user-images.githubusercontent.com/54119012/78939306-80472880-7a79-11ea-9ba9-0f4aba815510.png)

When I upload them it accepts them. I have tried putting the "area" and "perimeter" columns in multiple places and that does not fix the issue.
![polygonupload](https://user-images.githubusercontent.com/54119012/78939407-aec50380-7a79-11ea-80a3-7f9d99c4f371.jpg)
The project says that the polygons are there in the spot list, in the dataset menu, but not on the map. I have tried clicking on them to see if they were "there" but just invisible, but it didn't work. 
![polygon1](https://user-images.githubusercontent.com/54119012/78939944-a620fd00-7a7a-11ea-9455-b3a10931ee7b.png)
![polygon2](https://user-images.githubusercontent.com/54119012/78939966-b1742880-7a7a-11ea-90b7-f82f2f02c6c1.jpg)

The only hint of them I can get is when I click on the "show on the map" button from the spot page which then brings me to the map with no basemap. When I then uncheck the polygon database it will highlight the selected polygon but when I click off I am unable to re-click it from the map. 
![polygon3](https://user-images.githubusercontent.com/54119012/78940083-e6807b00-7a7a-11ea-9245-135e6976c461.png)

The shapefile I am trying to upload is attached. 
[FieldCampSinglePoly.zip](https://github.com/StraboSpot/strabo-desktop/files/4458633/FieldCampSinglePoly.zip)

**Comment by jasonash** [comment]
Hannah, this should be fixed now. Please try your upload again.

**Comment by hannahcunning** [comment]
Worked, Thanks!

**Comment by jasonash** [comment]
OK, please close.
